# Generated by Django 4.2.1 on 2023-05-04 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('world_rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='world_rank')),
            ],
        ),
    ]
