# Generated by Django 4.2.1 on 2023-05-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='university',
            table='university',
        ),
    ]
