# Generated by Django 4.2.1 on 2023-05-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_university_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='university',
            table=None,
        ),
    ]
